export default function TermsOfUse() {
  return (
    <>
      <h1>Terms of Use</h1>
      <p>Last updated: October 15, 2024</p>

      <h2>1. Acceptance of Terms</h2>
      <p>By accessing or using our website and services, you agree to be bound by these Terms of Use and our Privacy Policy. If you do not agree with any of these terms, you should discontinue using the service immediately.</p>

      <h2>2. Service Description</h2>
      <p>Our service provides users the ability to generate and analyze business ideas using AI. Users can also export AI-generated content to their personal Notion workspaces through the Notion OAuth authentication process. We do not collect, store, or retain any personal data from users as part of this process.</p>

      <h2>3. Notion Integration</h2>
      <p>By using the Notion export feature, you authorize us to connect to your personal Notion workspace using the OAuth process. This authorization is limited to exporting AI-generated content from our platform to your workspace. We do not access, process, or store any information from your Notion workspace outside of this operation. Your use of Notion is subject to their <a href="https://www.notion.so/Privacy-Policy-346d1a91cb384be5b2f525dc0e0293d8">Privacy Policy</a> and terms of service.</p>

      <h2>4. User Responsibilities</h2>
      <p>You are responsible for ensuring that any content you export or use within your Notion workspace complies with all applicable laws and regulations. We provide the content &quot;as-is&quot; and do not guarantee the accuracy, reliability, or completeness of the AI-generated content.</p>

      <h2>5. Limitation of Liability</h2>
      <p>We are not liable for any damages, including but not limited to loss of data, business interruption, or other losses resulting from the use or inability to use our services. The content generated by our AI is provided without warranties of any kind.</p>

      <h2>6. Intellectual Property</h2>
      <p>All content on our website, including but not limited to text, graphics, logos, and software, is owned by us or our licensors and is protected by intellectual property laws. You may not reproduce, distribute, or use any part of our website or content without express permission.</p>

      <h2>7. Use of LocalStorage</h2>
      <p>We use localStorage on your browser to temporarily store AI-generated content, ensuring that the content is available for export to Notion after you complete the authentication process. This local storage is cleared once the export is complete or after your session ends.</p>

      <h2>8. Changes to the Service</h2>
      <p>We reserve the right to modify or discontinue our service at any time, with or without notice. We are not liable for any changes, suspensions, or discontinuation of the service.</p>

      <h2>9. Disclaimer</h2>
      <p>The service is provided &quot;as is&quot; and &quot;as available,&quot; without any warranties of any kind, whether express or implied. We do not guarantee that the service will be available at all times, error-free, or free of viruses or other harmful components.</p>

      <h2>10. Governing Law</h2>
      <p>These Terms of Use are governed by and construed in accordance with the laws of [Your Country/Region], without regard to its conflict of law principles. Any disputes related to these terms or the use of our service will be resolved in the courts of [Your Jurisdiction].</p>

      <h2>11. Contact Information</h2>
      <p>If you have any questions or concerns about these Terms of Use, you can contact us at psalazardev@gmail.com.</p>
    </>
  );
}